import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
 
const gilroy = localFont({
  src: [
    { path: "./fonts/Gilroy-Medium.ttf", weight: "400", style: "normal" },
    { path: "./fonts/Gilroy-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "./fonts/Gilroy-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-gilroy",
});

const plexmono = localFont({
  src: [
    { path: "./fonts/IBMPlexMono-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/IBMPlexMono-Medium.ttf", weight: "500", style: "normal" },
  ],
  variable: "--font-plexmono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gilroy.variable} ${plexmono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
